version: '3.8'

services:
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: nginx
  todo-frontend:
    image: todo-frontend-dev
    build:
      context: todo-frontend
      dockerfile: dev.Dockerfile
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: todo-frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3000
      - PORT=3001

