name: Health check

on:
  push:
    branches:
      - master

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v1.2
      with:
        url: http://fs-2020-pokedex.herokuapp.com/health
        max-attempts: 3
        retry-delay: 5s
